//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp3Sync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp3Sync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0} files were copied on player.
        /// </summary>
        internal static string copiedFiles {
            get {
                return ResourceManager.GetString("copiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copy {1}{2}.
        /// </summary>
        internal static string copyFile {
            get {
                return ResourceManager.GetString("copyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination {0} is full{1}.
        /// </summary>
        internal static string destFull {
            get {
                return ResourceManager.GetString("destFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations capacity is {0} Mb.
        /// </summary>
        internal static string dstCapacity {
            get {
                return ResourceManager.GetString("dstCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files in destination.
        /// </summary>
        internal static string dstCount {
            get {
                return ResourceManager.GetString("dstCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete {0} check if it&apos;s not read only
        ///{1}.
        /// </summary>
        internal static string errorNoDelete {
            get {
                return ResourceManager.GetString("errorNoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The following files were not copied on the player (lack of place):.
        /// </summary>
        internal static string errorNoPlace {
            get {
                return ResourceManager.GetString("errorNoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra files will deleted.
        /// </summary>
        internal static string extradel {
            get {
                return ResourceManager.GetString("extradel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra files will be copied to {0}.
        /// </summary>
        internal static string extraFilesDest {
            get {
                return ResourceManager.GetString("extraFilesDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted free space on destination {0}{1}Mb.
        /// </summary>
        internal static string freeSpace {
            get {
                return ResourceManager.GetString("freeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hashs to compute, please wait.
        /// </summary>
        internal static string hashToDo {
            get {
                return ResourceManager.GetString("hashToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} files processed.
        /// </summary>
        internal static string hashWIP {
            get {
                return ResourceManager.GetString("hashWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read cache for {0}.
        /// </summary>
        internal static string readCache {
            get {
                return ResourceManager.GetString("readCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} extra or out of date files removed from player.
        /// </summary>
        internal static string removedFiles {
            get {
                return ResourceManager.GetString("removedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files in source.
        /// </summary>
        internal static string srcCount {
            get {
                return ResourceManager.GetString("srcCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source weights {0} Mb.
        /// </summary>
        internal static string srcWeight {
            get {
                return ResourceManager.GetString("srcWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1/3 -- Compute hash for files.
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Step 2/3 -- Remove extra files from destination
        ///.
        /// </summary>
        internal static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Step 3/3 -- Add new Files to destination
        ///.
        /// </summary>
        internal static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Player synchronized..
        /// </summary>
        internal static string synchroOK {
            get {
                return ResourceManager.GetString("synchroOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} already present in the collection\nas file: {1}.
        /// </summary>
        internal static string warnduplicate {
            get {
                return ResourceManager.GetString("warnduplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files won&apos;t be copied on the player, lack of place.
        /// </summary>
        internal static string warnLackPlace {
            get {
                return ResourceManager.GetString("warnLackPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cache file found for {0} please be patient,
        ///reconstructing is going to take a while.
        /// </summary>
        internal static string warnNocache {
            get {
                return ResourceManager.GetString("warnNocache", resourceCulture);
            }
        }
    }
}
